[package]

name = "rust-chess"
version = "0.0.1"
authors = ["Chris Gill <chrisfgill@gmail.com>"]

repository = "https://github.com/viperscape/rust-chess/"
keywords = ["chess", "game"]

license = "MIT"
description = "The Game of Chess, in Rust"

[dependencies.cubby]
git = "https://github.com/viperscape/cubby"

[dependencies.wire]
git = "https://github.com/TyOverby/wire"

[dependencies]
rustc-serialize = "*"
rand = "*"

[dependencies.pistoncore-event]
git = "https://github.com/PistonDevelopers/event"

[dependencies.glium]
git = "https://github.com/tomaka/glium"
[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
[dependencies.glium_macros]
git = "https://github.com/tomaka/glium"



[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston"

[dependencies.pistoncore-glutin_window]
git = "https://github.com/pistondevelopers/glutin_window"

[dependencies.shader_version]
git = "https://github.com/pistondevelopers/shader_version"